import vplib,logging
logging.basicConfig(level=logging.DEBUG)
server=input("gimee the vmesspro addr:")
print("start conn")
v=vplib.VmessPro(server)
print("conn succ")
o=v.connect()
print(f"nconn succ{o}")
o.connect("httpbin.org",80,"")
print(f"connserver")
o.send(b"GET /uuid HTTP/1.1\r\nHost: httpbin.org\r\nConnection: Close\r\n\r\n")
print(f"send")
a=o.recv()
print(f"{a.decode()}")
a=o.recv()
print(f"{a.decode()}")